#! /bin/bash

set -e

# pbuilder is mandatory
if [ -z "$( which pbuilder 2>&1 )" ]; then
	echo "You need pbuilder software, please install it before continuing" >&2
	exit 1
fi

# sudo must be enabled
if ! sudo /bin/true ; then
	echo "You need to enable sudo" >&2
	exit 1
fi

# Initialize pbuilder environment
if [ ! -e "/var/cache/pbuilder/base.tgz" ]; then
	sudo pbuilder create
fi

# Check options
while [ -n "$1" ]
do
	case "$1" in
		--update)
			sudo pbuilder --update
			;;
	esac
	shift
done

# Prepare source
perl Makefile.PL
make manifest

# Extract version from META.yml
VERSION=$( egrep '^version:' MYMETA.yml | cut -d' ' -f2 | tr -d 'v' )

# Prepare source archive removing debian forlder
TARFILE=../fusioninventory-agent_$VERSION.orig.tar
echo "Building $TARFILE ..."
git archive --format=tar --prefix=FusionInventory-Agent-$VERSION/ HEAD | \
	tar --delete "FusionInventory-Agent-$VERSION/debian/" > $TARFILE

# Add back files generated by make manifest
tar -rf $TARFILE --transform="s|^.|FusionInventory-Agent-$VERSION|" \
	./MANIFEST ./inc ./MYMETA.yml

# Finally compress orig tar file
echo "Compressing $TARFILE ..."
rm -f $TARFILE.xz
xz $TARFILE

set +e
echo "Building Debian package..."
pdebuild --use-pdebuild-internal

dh_clean
