use File::Which;
use LWP;
use Net::IP;
use UNIVERSAL::require;
use Text::Template;
use XML::TreePP;
use Socket::GetAddrInfo;
use Win32::TieRegistry;
use Win32::Job;
use Win32::OLE;
use Win32::OLE::Const;
use Win32::TieRegistry;
use Win32::Job;
use Parse::EDID;
use Compress::Zlib;
use HTTP::Daemon;
use IO::Socket::SSL;
use LWP::Protocol::https;
use English;
use Getopt::Long;
use Memoize;
use Pod::Usage;

use lib '.';
use lib 'lib';
my $file = shift;
require $file;
