#!/usr/bin/perl

use strict;
use warnings;

use English qw(-no_match_vars);
use Getopt::Long;
use Pod::Usage;

use FusionInventory::Agent::Task::NetDiscovery;

my $options = {
    community => 'public'
};

GetOptions(
    $options,
    'first=s',
    'last=s',
    'dictionnary=s',
    'community=s',
    'help',
) or pod2usage(-verbose => 0);

pod2usage(-verbose => 0) if $options->{help};

die "no first address" unless $options->{first};
die "no last address" unless $options->{last};

my $discovery = FusionInventory::Agent::Task::NetDiscovery->new(
    target => FusionInventory::Agent::Task::NetInventory::Target->new(
        dictionnary => $options->{dictionnary}
    )
);

$discovery->{options} = {
    NAME => 'NETDISCOVERY',
    PARAM => [
        {
            PID               => 1,
            THREADS_DISCOVERY => 1
        }
    ],
    RANGE => [
        {
            ID      => 1,
            IPSTART => $options->{first},
            IPEND   => $options->{last},
        }
    ],
    AUTHENTICATION => [
        {
            ID        => 1,
            COMMUNITY => $options->{community},
            VERSION   => 2
        }
    ]
};
$discovery->{client} =
    FusionInventory::Agent::Task::NetInventory::Client->new();
$discovery->{deviceid} = 'foo';

$discovery->run();

package FusionInventory::Agent::Task::NetInventory::Client;

sub new {
    my ($class) = @_;

    return bless {}, $class;
}

sub send {
    my ($self, %params) = @_;

    print $params{message}->getContent();
}

package FusionInventory::Agent::Task::NetInventory::Target;

use File::Basename;
use File::Temp qw/tempdir/;

use FusionInventory::Agent::Storage;

sub new {
    my ($class, %params) = @_;

    my $storage = FusionInventory::Agent::Storage->new(
        directory => $params{dictionnary} ?
            dirname($params{dictionnary}) : tempdir(CLEANUP => 1)
    );

    return bless {
        storage => $storage
    }, $class;
}

sub getStorage {
    my ($self, %params) = @_;

    return $self->{storage};
}

sub getUrl {
    my ($self, %params) = @_;

    return undef;
}

__END__

=head1 NAME

fusioninventory-discovery - Network inventory from command line

=head1 SYNOPSIS

fusioninventory-discovery [options] --start <start> --stop <stop>

  Options:
    -h --help      this menu
    --first start  IP range first address
    --last stop    IP range last address
    --dictionnary  dictionnary file
    --community    community string (default: public)
