=head1 NAME

agent.cfg - FusionInventory agent configuration file

=head1 SYNOPSIS

/etc/fusioninventory/agent.cfg

=head1 DESCRIPTION

On Unix, FusionInventory agent executables read their configuration from
F</etc/fusioninventory/agent.cfg>.

=head1 GENERIC OPTIONS

=over

=item B<server>

Specifies the server to use both as a controller for the agent, and as a
target for task execution output.

If the given value start with http:// or https://, it is assumed to be an URL,
and used directly. Otherwise, it is assumed to be an hostname, and interpreted
as http://hostname/ocsinventory.

Multiple values can be specified, using a comma as a separator.

=item B<no-mdule>

Disables given module.

Multiple values can be specified, using a comma as a separator.

=item B<proxy>

Specifies the URL of the HTTP proxy to use. By default, the agent uses
HTTP_PROXY environment variable.

=item B<user>

Specifies the user to use for HTTP authentication on the server.

=item B<password>

Specifies the password to use for HTTP authentication on the server.

=item B<ca-cert-dir>

Specifies the directory containing indexed Certification Authority (CA)
certificates.

=item B<ca-cert-file>

Specifies the file containing aggregated Certification Authority (CA)
certificates.

=item B<no-ssl-check>

Disables server SSL certificate validation. The default is 0 (false).

=item B<timeout>

Specifies a timeout, in seconds, for server connections.

=item B<no-httpd>

Disables the embedded web interface, used to receive execution requests from the
server. The default is 0 (false).

=item B<httpd-ip>

Specifies the network interface to use for the embedded web interface. The
default is to use all available ones.

=item B<httpd-port>

Specifies the network port to use for the embedded web interface. The default
is 62354.

=item B<httpd-trust>

Specifies which IP address should be trusted, for execution requests. The
default is to only accept requests from the control servers.

All formats supported by L<Net::IP> can be used (IP addresses, IP addresses
ranges, networks in CIDR notatation), as well as hostnames.

Multiple values can be specified, using a comma as a separator.

=item B<logger>

Specifies the logger backend to use. The possible values are:

=over 4

=item * file: log messages in a file.

=item * stderr: log messages directly in the console.

=item * syslog: log messages through the local syslog server.

=back

Multiple values can be specified, using a comma as a separator.

=item B<logfile>

Specifies the file to use for the file logger backend.

=item B<logfile-maxsize>

Specifies the maximum size for the log file, in MB.  When the max size is
reached, the file is truncated. The default is unlimited.

=item B<logfacility>

Specifies the syslog facility to use for the syslog logger backend. The default
is LOG_USER.

=item B<color>

Enables color display for the stderr logger backend.

This directive is used on Unix only.

=item B<debug>

Specifies the level of verbosity for log content. The possible values are:

=over 4

=item * 0: basic agent processing

=item * 1: extended agent processing

=item * 2: messages exchanged with the server

=item * 3: additional traces for some external libraries as Net::SSLeay

=back

=back

=head1 INVENTORY TASK SPECIFIC OPTIONS

=over

=item B<tag>

Specifies an arbitrary string to add to output. This can be used as an
additional decision criteria on server side.

=item B<no-category>

Disables given category in output. The possible values are:

=over 4

=item * printer

=item * software

=item * environment

=item * process

=item * user

=back

Multiple values can be specified, using a comma as a separator.

=item B<scan-homedirs>

Enables scanning user home directories for virtual machines. The default is 0
(false).

=item B<scan-profiles>

Enables scanning user profiles for softwares. The default is 0
(false).

=item B<collect-timeout>

Specifies the timeout for task modules execution.

=item B<additional-content>

Specifies an XML file whose content will be automatically merged with output.

=back

=head1 INVENTORY TASK SPECIFIC OPTIONS

=over

=item B<no-p2p>

Disables peer to peer for downloading files.

=back
