Name:           perl-FusionInventory-Agent-Task-OcsDeploy
Version:        1.0.2
Release:        1%{?dist}
Summary:        OCS Inventory NG Software deployment support for FusionInventory Agent
Summary(fr):    Gestion du déploiement logiciel OCS Inventory NG avec FusionInventory
License:        GPLv2+
Group:          Development/Libraries

URL:            http://search.cpan.org/dist/FusionInventory-Agent-Task-OcsDeploy/
Source0:        http://search.cpan.org/CPAN/authors/id/G/GO/GONERI/FusionInventory-Agent-Task-OcsDeploy-%{version}.tar.gz

BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch

BuildRequires:  perl(Archive::Extract)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Copy::Recursive)
BuildRequires:  perl(FusionInventory::Agent) >= 2.0
BuildRequires:  perl(XML::Simple)
Requires:       perl(Archive::Extract)
Requires:       perl(File::Copy::Recursive)
Requires:       perl(FusionInventory::Agent) >= 2.0
Requires:       perl(XML::Simple)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}


%description
With this module, FusionInventory Agent can accept software deployment
request from an OCS Inventory server NG.


%description -l fr
Avec ce module, l'agent FusionInventory peut traiter les ordres de
déploiement de logiciel envoyés par un serveur OCS Inventory NG.


%prep
%setup -q -n FusionInventory-Agent-Task-OcsDeploy-%{version}


%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}


%install
rm -rf $RPM_BUILD_ROOT

make pure_install DESTDIR=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*


%check
make test


%clean
rm -rf $RPM_BUILD_ROOT


%files
%defattr(-,root,root,-)
%doc AUTHORS Changes LICENSE README THANKS
%{perl_vendorlib}/FusionInventory/Agent/Task/OcsDeploy.pm
%{_mandir}/man3/Fusion*


%changelog
* Fri May 07 2010 Remi Collet <Fedora@famillecollet.com> - 1.0.2-1
- Specfile autogenerated by cpanspec 1.78.
- spec cleanup + translation

