#!/usr/bin/perl

use strict;
use warnings;

use File::Find;

open AGENT, ">debian/fusioninventory-agent.install";
open AGENT_TASK_DEPLOY, ">debian/fusioninventory-agent-task-deploy.install";
open AGENT_TASK_NETWORK, ">debian/fusioninventory-agent-task-network.install";
open AGENT_TASK_ESX, ">debian/fusioninventory-agent-task-esx.install";
open AGENT_TASK_COLLECT, ">debian/fusioninventory-agent-task-collect.install";

find({ wanted => \&wanted, no_chdir=>1}, 'blib');
sub wanted {
    my $t = $File::Find::name;
    return unless -f $t;
    $t =~ s,blib/,usr/share/fusioninventory/,;
    $t =~ s,usr/share/fusioninventory/script/,usr/bin/,;
    if (/\/man1\//) {
        # dh_installmans
    } elsif ($t =~ /fusioninventory-net/ || $t =~ /FusionInventory\/Agent\/SNMP/) {
        print AGENT_TASK_NETWORK "$t\n";
    } elsif ($t =~ /FusionInventory\/Agent\/Tools\/Hardware/) {
        print AGENT_TASK_NETWORK "$t\n";
    } elsif ($t =~ /FusionInventory\/Agent\/Task\/Net/) {
        print AGENT_TASK_NETWORK "$t\n";
    } elsif ($t =~ /fusioninventory-esx/) {
        print AGENT_TASK_ESX "$t\n";
    } elsif ($t =~ /FusionInventory\/Agent\/Task\/ESX/) {
        print AGENT_TASK_ESX "$t\n";
    } elsif ($t =~ /FusionInventory\/Agent\/Task\/Deploy/) {
        print AGENT_TASK_DEPLOY "$t\n";
    } elsif ($t =~ /FusionInventory\/Agent\/Task\/Collect/) {
        print AGENT_TASK_COLLECT "$t\n";
    } elsif ($t !~ m,/.exists,) {
        # Skip .exists files
        print AGENT "$t\n";
    }
};

print AGENT "etc/agent.cfg /usr/share/fusioninventory/etc\n";
print AGENT "usr/share/fusioninventory/edid.ids\n";
print AGENT "usr/share/fusioninventory/sysobject.ids\n";
print AGENT "usr/share/fusioninventory/html\n";
print AGENT "contrib/unix/fusioninventory-agent.service lib/systemd/system\n";
